# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

FROM java:8
EXPOSE 8080
ADD /built-project/springbootsimplerest-0.0.1-SNAPSHOT.jar springbootsimplerest-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","springbootsimplerest-0.0.1-SNAPSHOT.jar"]
