# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templatess
# and open the template in the editor.

FROM java
EXPOSE 8080
ADD /built-project/demo.jar demo.jar
ENTRYPOINT ["java","-jar","demo.jar"]
