resources:
- name: SpringBootSimpleRest
  type: git
  source:
    uri: https://github.com/dhaneshande/SpringBootConcoursePipeline.git
    branch: master
- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: SpringBootSimpleRest, trigger: true}
  - task: build
    privileged: true
    file: SpringBootSimpleRest/ci/build.yml
  - put: resource-deploy-web-app
    params:
      manifest: SpringBootSimpleRest/manifest.yml
      path: built-project/demo.jar
