resources:
- name: SpringBootSimpleRest
  type: git
  source:
    uri: https://github.com/dhaneshande/SpringBootConcoursePipelineWithVersioning.git
    branch: master
- name: hello-world-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: SpringBootSimpleRest, trigger: true}
  - task: build
    privileged: true
    file: SpringBootSimpleRest/ci/build.yml
  - put: resource-deploy-web-app
    params:
      manifest: SpringBootSimpleRest/manifest.yml
      path: built-project/demo.jar
